name: Compile Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update apt
        run: |
          grep -m1 '^Date:' /var/lib/apt/lists/*InRelease
      - uses: hendrikmuhs/ccache-action@v1.2.19
      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake
      - name: Configure
        run: cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache .
      - name: Build
        run: make
      - name: Run
        run: ./hello
