name: Compile Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - uses: Andrej730/ccache-action@apt-update
      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake
      - name: Configure
        run: cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache .
      - name: Build
        run: make
      - name: Run
        run: ./hello
