name: Hello World

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to use in messages'
        required: false
        default: 'World'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: echo "Hello ${{ inputs.name }}"
  goodbye:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Goodbye
        run: echo "Goodbye ${{ inputs.name }}"
